name: ci
on: push
jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.9
      - run: |
          export GOPATH="$HOME/gopath"
          export PATH="$GOPATH/bin:$PATH"
          ls -l
          make
